### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

# รสธร มะลิลา  660510743

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [2]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [3]:
a = torch.tensor(8)
b = torch.tensor(9)
print(a)
print(b)
print(a+b)

tensor(8)
tensor(9)
tensor(17)


### Convert a tensor to scalar

In [4]:
a.item()

8

### Creating 2D tensor

In [5]:
A = torch.tensor([[1, 2], [3, 4]])
print(A)

tensor([[1, 2],
        [3, 4]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [6]:
A.numpy()

array([[1, 2],
       [3, 4]])

### Convert from numpy array to tensor

In [7]:
B = np.array([[1, 2], [3, 4]])

C = torch.from_numpy(B)
print(C)

tensor([[1, 2],
        [3, 4]])


## Basic operations

In [8]:
D = 2*C

E = C - 10

print(D)
print(E)

tensor([[2, 4],
        [6, 8]])
tensor([[-9, -8],
        [-7, -6]])


### Matrix multiplication

In [9]:
print(torch.matmul(D, E))
print(torch.mm(D, E))
print(D @ E)

tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])


### Matrix transpose

In [10]:
print(C)
print( C.t() )

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


## Creating a specific type of tensor

In [11]:
# print(torch.zeros(2,3))
# print(torch.ones(2,3))
# print(torch.rand(2,3))
# print(torch.randn(2,3))  # sample each number from N(0, 1)
# print(torch.arange(9))

## Tensor's shape

### Checking the shape of a tensor

In [12]:
F = torch.zeros((4, 5))
print(F.shape)
print(F.size())

torch.Size([4, 5])
torch.Size([4, 5])


### Changing the shape of a tensor

In [13]:
G = torch.arange(6)
print(G.view(2, 3))
print(G.reshape(2, 3))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [14]:
H = torch.arange(6)
I = torch.stack([H, H, H, H], axis=0)
J = torch.stack([H, H, H, H], axis=1)
print(I)
print(J)

tensor([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]])
tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5]])


In [15]:
# concatenate

I = torch.cat([H, H, H, H], axis=0)
print(I)
# J = torch.cat([H, H, H, H], axis=1)
#print(J)

tensor([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])


### Squeezing a tensor (removing an extra dimension)

In [16]:
# [[1,2]] this is (1,2) tensor, want (2,)
print("H=", H) # shape = (6,)
K = H.reshape(1,6)
print("K=", K)
print(K.shape)

H= tensor([0, 1, 2, 3, 4, 5])
K= tensor([[0, 1, 2, 3, 4, 5]])
torch.Size([1, 6])


In [17]:
print(K.squeeze())

tensor([0, 1, 2, 3, 4, 5])


In [18]:
# H.shape = (6, )
L = H.unsqueeze(axis=0)  # L.shape(1, 6)
M = H.unsqueeze(axis=1)  # L.shape(6, 1)
print(L)
print(M)

tensor([[0, 1, 2, 3, 4, 5]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])


## Indexing

In [19]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


## PyTorch and GPU

check if GPU is available

In [20]:
torch.cuda.is_available()

True

In [21]:
Q = torch.tensor([1, 2, 3])
print(Q.device)

cpu


In [22]:
R = Q.to('cuda')
print(Q.device)
print(R.device)

cpu
cuda:0


In [23]:
R.cpu().numpy()

array([1, 2, 3])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [24]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [26]:

X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]], dtype=torch.float32)
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]], dtype=torch.float32)
print( X)


# สร้างค่าสัมประสิทธิ์ (b) และค่าความคลาดเคลื่อน (e) แบบสุ่มเพื่อสร้างข้อมูล y
b = torch.tensor([[0.5], [1.2], [0.8], [2.0]], dtype=torch.float32)
e = torch.randn(3, 1)

# คำนวณค่า  y = Xb + e
y = torch.matmul(X, b) + e
print("\nค่า y ที่สร้างขึ้น:\n", y)

# b_hat = (X^T * X)^-1 * X^T * y
XT = X.T
XTX_inv = torch.inverse(torch.matmul(XT, X))
XTy = torch.matmul(XT, y)
b_hat = torch.matmul(XTX_inv, XTy)

print( b_hat)

# ใช้ b_hat ที่ได้มาทำนายค่า y (y_hat)
y_hat = torch.matmul(X, b_hat)
print( y_hat)

# วัดผลMean Squared Error (MSE)
mse = torch.mean((y - y_hat)**2)
print(mse.item())

tensor([[2., 3., 2.],
        [4., 6., 7.],
        [7., 2., 4.]])
tensor([[1., 2., 3., 2.],
        [1., 4., 6., 7.],
        [1., 7., 2., 4.]])

ค่า y ที่สร้างขึ้น:
 tensor([[ 9.7669],
        [23.7692],
        [16.9044]])
tensor([[ 1.1279e+02],
        [-9.2461e-02],
        [-4.3575e+01],
        [ 2.5751e+01]])
tensor([[ 33.3860],
        [ 31.2300],
        [128.0000]])
4318.58349609375
